'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: (queryInterface, Sequelize) => {
    return Promise.all([
      queryInterface.bulkInsert(
        'goods',
        [
          {
            "id": 1,
            "name": "Accesorios para sistemas de riego",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 2,
            "name": "Alambre de púas, alambrón",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 3,
            "name": "Artículos de plástico excepto juguetes",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 4,
            "name": "Cajero automático y/o accesorios y/o repuestos",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 5,
            "name": "Cartones,  cajas, cajones, bolsas y otros contenedores para empacar",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 6,
            "name": "Concentradores de oxigeno",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 7,
            "name": "Corcho y artículos de corcho",
            "group": "1",
            "percentage": 0.0138,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 8,
            "name": "Dispensadores de combustible (para estaciones de servicio)",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 9,
            "name": "Envases y productos  desechables",
            "group": "1",
            "percentage": 0.0138,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 10,
            "name": "Equipos topográficos",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 11,
            "name": "Extintores (cilindros vacíos)",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 12,
            "name": "Papel aluminio",
            "group": "1",
            "percentage": 0.0138,
            "imp_exp_percentage": 0.25,
            "is_active": 1,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 13,
            "name": "Papel y/o  cartón",
            "group": "1",
            "percentage": 0.0199,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 14,
            "name": "Pasta de madera o de otro material de celulosa fibrosa",
            "group": "1",
            "percentage": 0.0199,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 15,
            "name": "Pegamentos",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 16,
            "name": "Pelucas",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 17,
            "name": "Plástico para embalar alimentos",
            "group": "1",
            "percentage": 0.0138,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 18,
            "name": "Plásticos y sus manufacturas",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 19,
            "name": "Prótesis",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 20,
            "name": "Rodillos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 21,
            "name": "Vitrinas",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 22,
            "name": "Aditamentos y equipo para equitación",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 23,
            "name": "Encajes, tapices;  bordados",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 24,
            "name": "Utensilios de Mesa, cocina o de otros artículos de uso doméstico, de hierro o acero; excepto electrodomésticos",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 25,
            "name": "Velas",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 26,
            "name": "Menaje de casa o habitación",
            "group": "1",
            "percentage": 0.0138,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 27,
            "name": "Cable sin cobre",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 28,
            "name": "Cáscara de nuez",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 29,
            "name": "Equipo de buceo",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 30,
            "name": "Harina de pescado",
            "group": "1",
            "percentage": 0.0096,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 31,
            "name": "Harina vegetal",
            "group": "1",
            "percentage": 0.0096,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 32,
            "name": "Láminas de seguridad",
            "group": "1",
            "percentage": 0.0096,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 33,
            "name": "Lonas",
            "group": "1",
            "percentage": 0.0138,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 34,
            "name": "Luminarias",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 35,
            "name": "Madera y o sus manufacturas",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 36,
            "name": "Materia prima para farmacéuticos: Ingredientes activos para farmacéuticos , no fabricados totalmente",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 37,
            "name": "Materia prima para la industria de perfumes",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 38,
            "name": "Semillas y frutos oleaginosos",
            "group": "1",
            "percentage": 0.0096,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 39,
            "name": "Tripas de colágeno",
            "group": "1",
            "percentage": 0.008,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería no permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 40,
            "name": "Lacas, gomas",
            "group": "1",
            "percentage": 0.0199,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 41,
            "name": "Manómetros",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 42,
            "name": "Materiales para la construcción: excepto ferretería",
            "group": "1",
            "percentage": 0.0115,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 43,
            "name": "Otros",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 44,
            "name": "Cereales no a granel",
            "group": "1",
            "percentage": 0.008,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 45,
            "name": "Herrajes",
            "group": "1",
            "percentage": 0.0138,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 46,
            "name": "Lubricantes y aditivos en isotanques",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 47,
            "name": "Manufacturas de paja, cestería y mimbre",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 48,
            "name": "Maquinaria para la industria agrícola",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 49,
            "name": "Maquinaria para la industria petrolera",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 50,
            "name": "Maquinaria para la industria textil",
            "group": "1",
            "percentage": 0.0199,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 51,
            "name": "Maquinaria para la industria grafica",
            "group": "1",
            "percentage": 0.0199,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 52,
            "name": "Maquinaria para la construcción",
            "group": "1",
            "percentage": 0.0199,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 53,
            "name": "Máquinas dispensadoras de productos",
            "group": "1",
            "percentage": 0.0115,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 54,
            "name": "Máquinas y aparatos mecánicos",
            "group": "1",
            "percentage": 0.0115,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 55,
            "name": "Motores para maquinaria",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 56,
            "name": "Partes y piezas para trofeos",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 57,
            "name": "Productos para señalización vial",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 58,
            "name": "Refrigeradores o Congeladores industriales",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 59,
            "name": "Repuestos , Partes y piezas para maquinaria",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 60,
            "name": "Repuestos para aviones",
            "group": "1",
            "percentage": 0.0166,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 61,
            "name": "Repuestos para barcos",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 62,
            "name": "Yates y otras embarcaciones bajo cubierta",
            "group": "1",
            "percentage": 0.0138,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 63,
            "name": "Acero (laminas, bobinas o barras)",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 64,
            "name": "Aluminio (laminas, barras, bobinas y lingotes)",
            "group": "1",
            "percentage": 0.0115,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 65,
            "name": "Caucho y sus manufacturas",
            "group": "1",
            "percentage": 0.0199,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 66,
            "name": "Chatarra de metal",
            "group": "1",
            "percentage": 0.0115,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 67,
            "name": "El hidróxido de sodio (soda cáustica); hidróxido de potasio (potasio caustico)",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 68,
            "name": "Hierro (laminas, bobinas o barras)",
            "group": "1",
            "percentage": 0.0287,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 69,
            "name": "Muebles de oficina",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 70,
            "name": "Muebles, camas o colchones nuevos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 71,
            "name": "Piso flotante - vinyl",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 72,
            "name": "Productos químicos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 73,
            "name": "Tubería de PVC",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 74,
            "name": "Tuberías de metal",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 75,
            "name": "Zinc en lingote",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 1,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 76,
            "name": "Aparatos de oxígeno terapia",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 77,
            "name": "Balanzas eléctricas y accesorios",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 78,
            "name": "Bombas de agua y/o líquidos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 79,
            "name": "Fibras ópticas",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 80,
            "name": "Fibras Textiles",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 81,
            "name": "Filtros de agua",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 82,
            "name": "Libros, periódicos , fotos , imágenes o productos relacionados",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 83,
            "name": "Manufacturas de plástico",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 84,
            "name": "Materiales didácticos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 85,
            "name": "Útiles escolares",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 86,
            "name": "Bicicletas",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 87,
            "name": "Equipo de oficina, sin incluir mobiliario de oficina",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 88,
            "name": "Equipos de protección personal",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 89,
            "name": "Equipos de protección personal (cascos, botas)",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 90,
            "name": "Equipos de seguridad  (alarmas, sensores, cámaras, circuito cerrados, red eléctrica)",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 91,
            "name": "Equipos GPS",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 92,
            "name": "Instrumentos musicales; partes y accesorios",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 93,
            "name": "Insumos para seguridad industrial (cascos, botas, guantes, trajes)",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 94,
            "name": "Mochilas",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 95,
            "name": "Pilas y baterías de un solo uso",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 96,
            "name": "Rollos de plástico",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 97,
            "name": "Alfombras, cobijas, cortinas , colchas, edredones",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 98,
            "name": "Cortinas y black-outs; rodapiés de cama.",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 99,
            "name": "Gafas y similares,",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 100,
            "name": "Materiales y equipos para  ejercicio físico general , gimnasia, atletismo",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 101,
            "name": "Ropa y accesorios",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 102,
            "name": "Válvulas",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 103,
            "name": "Alimentos en conserva, o enlatados incluyendo jugos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 104,
            "name": "Artículos de aseo personal",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 105,
            "name": "Artículos de limpieza",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 106,
            "name": "Artículos de tocador",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 107,
            "name": "Artículos sanitarios y sus partes, de hierro o acero.",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 108,
            "name": "Instrumentos e insumos médicos o quirúrgico",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 109,
            "name": "Jabón, preparaciones para lavar",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 110,
            "name": "Juguetes, juegos y artículos para recreo o deporte",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 111,
            "name": "Leche o jugos en tetra pack",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 112,
            "name": "Material eléctrico",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 113,
            "name": "Miel natural",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 114,
            "name": "Vitaminas en general",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 0,
            "obs": "Mercadería Permitida",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 115,
            "name": "Accesorios de vehículos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 116,
            "name": "Aceite de oliva",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 117,
            "name": "Cemento",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 118,
            "name": "Lubricantes y aditivos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 119,
            "name": "Motores para vehículos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 120,
            "name": "Preparaciones alimenticias obtenidas con cereales o productos de cereales",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 121,
            "name": "Preparados para animales: Residuos y desperdicios de las industrias alimentarias; preparados para animales",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 122,
            "name": "Repuestos Automotrices",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 123,
            "name": "Tintas, pinturas o barnices",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 124,
            "name": "Fertilizantes",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 125,
            "name": "Insecticidas y Fungicidas",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 126,
            "name": "Maquinaria y equipos médicos o quirúrgico",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 127,
            "name": "Máquinas de coser y/o sus partes",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 128,
            "name": "Bebidas, bebidas alcohólicas, Cerveza de malta y vino",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 129,
            "name": "Bisutería",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 130,
            "name": "Cueros y pieles sin curtir",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 131,
            "name": "Manufacturas de cuero; artículos de guarnicionería y talabartería",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 132,
            "name": "Motos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 133,
            "name": "Neumáticos nuevos de caucho.",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 134,
            "name": "Poliéster o poliestireno",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 135,
            "name": "Resinas",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 136,
            "name": "Transformadores eléctricos y  convertidores eléctricos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 2,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 137,
            "name": "Herramientas y artículos de ferretería",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 138,
            "name": "Calderas",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 139,
            "name": "Material de desecho",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 140,
            "name": "Telas y/o cuero, calzado",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 141,
            "name": "Arboles vivos y otras plantas, bulbos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 142,
            "name": "Cámaras digitales y de vídeo, cámaras fotográficas y accesorios, radios de comunicación y sus partes, tablets y reproductores de música portátiles",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 143,
            "name": "Confitería",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 144,
            "name": "Helados",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 145,
            "name": "Henequén",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 146,
            "name": "Hortalizas secas, enteras cortadas, trituradas o pulverizadas",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 147,
            "name": "Huevos de Ave",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 148,
            "name": "Perfumes",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 149,
            "name": "Copra",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 150,
            "name": "Computadores, laptops  y sus componentes",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 151,
            "name": "Gas de petróleo y demás hidrocarburos gaseosos.",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 152,
            "name": "Electrodomésticos en general, equipos de televisión y vídeo",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 153,
            "name": "Productos a granel",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 154,
            "name": "Vidrio",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 155,
            "name": "Contenedores",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 156,
            "name": "Algodón",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 157,
            "name": "Animales vivos, peces vivos.",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 158,
            "name": "Azúcar, cacao y café en general",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 159,
            "name": "Armas, municiones, explosivos y productos pirotécnicos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 160,
            "name": "Carbón; briquetas, ovoides",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 161,
            "name": "Cigarros, puros,  cigarrillos, tabaco en general",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 162,
            "name": "Combustible",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 163,
            "name": "Coque, o  semi-coque de carbón de lignito o turba",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 164,
            "name": "Elementos químicos radiactivos e isótopos radiactivos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 165,
            "name": "Aparatos eléctricos de telefonía,  teléfonos celulares y sus accesorios",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 166,
            "name": "Farmacéuticos, medicinas producidos bajo prescripción y de venta libre",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 167,
            "name": "Níquel, sus concentrados y manufacturas",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 168,
            "name": "Productos que requieren refrigeración",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 169,
            "name": "Vehículos livianos, pesados y motocicletas",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 170,
            "name": "Cobre y sus manufacturas, cable con cobre, minerales de cobre y sus concentrados",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 171,
            "name": "Videojuegos",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 172,
            "name": "dinero en efectivo y valores, piedras y metales preciosos, joyas, relojes",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 173,
            "name": "Obras de arte, piezas de colección y antigüedades",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },
          {
            "id": 174,
            "name": "Tarjetas de crédito",
            "group": "1",
            "percentage": 0.0239,
            "imp_exp_percentage": 0.25,
            "is_moderate": 1,
            "obs": "Mercadería Riesgo Alto",
            "is_active": 1,
            "type_of_risk": 3,
            "createdAt": new Date(),
            "updatedAt": new Date()
          },

        ],
        { truncate: true }
      ),
    ]);
  },
  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('goods', null, { truncate: true });
  }
};
