name: production

on: 
   push:
      branches: 
        - master
    
jobs:
  build:
    runs-on: self-hosted
      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up AWS CLI
            uses: aws-actions/configure-aws-credentials@v1
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
                aws-region: us-east-2
            
          - name: ecr login
            run: |
                aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 637527414831.dkr.ecr.us-east-2.amazonaws.com
                echo "ligin success"
                docker build -t sgros .
                echo "build success"
                docker tag sgros:latest 637527414831.dkr.ecr.us-east-2.amazonaws.com/sgros:latest
                echo "tag success"
                docker push 637527414831.dkr.ecr.us-east-2.amazonaws.com/sgros:latest
                echo "push success"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key for EC2 access 
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
        
      - name: SSH into EC2 and execute commands 
        run: |
                    ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
                    set -e
                    echo "Docker Login"
                    aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 637527414831.dkr.ecr.us-east-2.amazonaws.com
                    docker pull 637527414831.dkr.ecr.us-east-2.amazonaws.com/sgros:latest
                    echo "pull done"
                    docker logout 
                    echo "removing older container"
                    docker rm -f sgros-react-webapp
                    echo "done"
                    echo "Running New container"
                    sudo docker run -d --name sgros-react-webapp -p 3000:3000 637527414831.dkr.ecr.us-east-2.amazonaws.com/sgros:latest
                    echo "Done" 
                    docker system prune -a --force 
                    '
